server:
  port: 8200

# eureka配置
eureka:
  client:
    service-url:
      #服务注册到eureka的地址
      defaultZone: http://localhost:8100/eureka
  instance:
    #该服务注册到eureka服务端的唯一的实例ID
    instance-id: wechat-1
    #是否显示ip地址
    prefer-ip-address: true
    #eureka客户端需要多长时间发送心跳给eureka服务器,表明它仍然活着,默认为30 秒(与下面配置的单位都是秒)
#    lease-renewal-interval-in-seconds: 30
    #eureka服务器在接收到实例的最后一次发出的心跳后,需要等待多久才可以将此实例删除,默认为90秒
#    lease-expiration-duration-in-seconds: 90

spring:
  application:
    #此服务注册到eureka服务端的名字
    name: app-wechat

# swagger配置
swagger:
  base-package: com.mobei.wechat.service
  title: SpringCloud2.X-微服务电商-微信服务接口
  description: 基于微服务的应用
  version: 1.1
  contact:
    name: mobei
    email: test@123.com
#  terms-of-service-url: 服务条款,好像没什么用