server:
  port: 8400
spring:
  application:
    name: app-configserver
# 设置配置中心地址
  cloud:
    config:
      server:
        git:
          uri: http://192.168.127.51/root/config.git #配置文件在远程仓库的地址,比如我这里放在github上